[workspace]

[package]
name = "ping-pong-enclave"
version = "0.5.1"
edition = "2021"
authors = ["Informal Systems <hello@informal.systems>"]

[features]
mock = ["quartz-common/mock-cw", "quartz-common/mock-enclave"]
default = []

[dependencies]
# external
async-trait = "0.1.81"
anyhow = { version = "1.0.86" }
clap = { version = "4.1.8", default-features = false, features = [
  "derive",
  "std",
] }
color-eyre = { version = "0.6.2", default-features = false }
ecies = { version = "0.2.3", default-features = false, features = ["pure"] }
env_logger = { version = "0.11", default-features = false }
hex = { version = "0.4.3", default-features = false }
k256 = { version = "0.13.2", default-features = false, features = [
  "ecdsa",
  "alloc",
] }
serde = { version = "1.0.203", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.94", default-features = false, features = [
  "alloc",
] }
reqwest = "0.12.7"
tokio = { version = "1.39.2", default-features = false, features = [
  "macros",
  "rt",
] }
tonic = { version = "0.13.1", default-features = false, features = [
  "codegen",
  "prost",
  "transport",
] }
tracing = "0.1.39"

# cosmos
cosmrs = { version = "0.22.0", default-features = false, features = ["getrandom"]}
cosmwasm-std = { version = "3", default-features = false, features = [
  "std",
] }
tendermint = { version = "=0.40.4", default-features = false }
tendermint-rpc = { version = "=0.40.4", default-features = false }
tendermint-light-client = { version = "=0.40.4", default-features = false, features = [
  "rust-crypto",
] }
ping-pong-contract = { path = "../contracts", default-features = false }

# quartz
# TODO: Until the repo is public, let's use the relative path
cw-client = { path = "../../../crates/utils/cw-client", default-features = false }
quartz-common = { version = "0.5.1", features = ["full"] }

# patch indirect deps
getrandom = { version = "0.2.15", features = ["js"] }
backtrace = "=0.3.74"
url = "=2.5.0"
base64ct = "=1.7.3"
ed25519-zebra = "=4.0.3"

[dev-dependencies]
cw-multi-test = "2.1.0"

[patch.crates-io]
cw-client = { path = "../../../crates/utils/cw-client" }
quartz-common = { path = "../../../crates/common" }
quartz-tm-prover = { path = "../../../crates/utils/tm-prover" }
