[package]
name = "transfers-contract"
version = "0.5.1"
edition = "2021"
rust-version = "1.75.0"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/informalsystems/cycles-quartz"
homepage = "https://cycles.money"
authors = ["Informal Systems <hello@informal.systems>"]
exclude = ["contract.wasm", "hash.txt"]
description = """
"""

[[bin]]
name = "schema"
path = "bin/schema.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
mock-sgx = ["quartz-contract-core/mock-sgx"]
library = []

[dependencies]
# external
thiserror = { version = "2" }

# cosmwasm
cosmwasm-std = { version = "3", default-features = false, features = [
    "std",
] }
cosmwasm-schema = { version = "3", default-features = false }
cw-storage-plus = { version = "3", default-features = false }
cw-utils = { version = "3", default-features = false }

# quartz
quartz-contract-core = { path = "../../../crates/contracts/core" }
quartz-contract-core-derive = { path = "../../../crates/contracts/core/derive" }

# patch indirect deps
getrandom = { version = "0.2.15", features = ["js"] }
base64ct = "=1.7.3"
ed25519-zebra = "=4.0.3"

[dev-dependencies]
cw-multi-test = { version = "3", default-features = false }
serde_json = "1.0.122"
