[package]
name = "quartz-contract-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories = ["cryptography::cryptocurrencies", "wasm"]
keywords = ["cosmos", "cosmwasm", "quartz", "tee", "dstack"]
readme = "README.md"
description = """
A CosmWasm framework for securely interacting with TEE enclaves (dstack/TDX).
"""

[features]
default = []
mock = []
std = ["k256/std", "serde/std", "serde_json/std", "sha2/std", "cosmwasm-std/std", "cosmwasm-std/stargate"]
library = []

[dependencies]
# external
hex.workspace = true
k256.workspace = true
prost = { workspace = true, features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

# cosmos
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true
cosmwasm-std = { workspace = true, features = ["stargate", "cosmwasm_2_0"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)', 'cfg(kani_slow)'] }

[dev-dependencies]
serde_json.workspace = true
